### ISSUE TITLE
element/pattern etc specific styles

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/styleguide-starterpack#2]
Currently these are styled throughout with a similar styles but different classes, we should use something that's a bit better.

**Comment by streeetlamp** [comment]
![0r9ifff](https://cloud.githubusercontent.com/assets/1740634/5906454/b62df210-a565-11e4-8fec-1ad3f9f7c10d.gif)


gimme me a quick example

**Comment by luetkemj** [comment]
```scss
.element{
  @include container($wrapper-width);

  border: 1px solid $lightgrey;
  margin-bottom: 2em;
  padding: 2em;

  ul{
    margin: 0 0 0 0;
    padding: 0 0 0 0;
    list-style-type: none;
  }
}

//and

.pattern{
  @include container($wrapper-width);

  border: 1px solid $lightgrey;
  margin-bottom: 2em;
  padding: 2em;

  ul{
    margin: 0 0 0 0;
    padding: 0 0 0 0;
    list-style-type: none;
  }
}
```
